<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPPWxbHk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPPWxbHk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPPWxbHk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPPWxbHk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPPWxbHk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PPWxbHk',
    'container.build_id' => 'c6b6455c',
    'container.build_time' => 1527279825,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPPWxbHk');
